apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc-jegan # Replace 'jegan' with your name

      containers:
      - image: bitnami/mariadb:latest
        name: mariadb

        env:
        - name: MARIADB_ROOT_PASSWORD
          value: root@123

        - name: MARIADB_DATABASE
          value: bitnami_wordpress

        volumeMounts:
        - name: mariadb-storage
          mountPath: /bitnami/mariadb/data
