apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc-{{ .Values.pvLabel }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.pvLabel }} 
      tier: be
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
