apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv-{{.Values.pvLabel}}
  labels:
    name: {{.Values.pvLabel}}
    tier: fe
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce # All Pods from the same node can access this Persistent volume(PV)
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: {{ .Values.nfsServerIP }} 
    path: {{ .Values.nfsWordpressPVPath }} 
