apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-jegan # Replace 'jegan' with your name 
spec:
  capacity:
    storage: 100Mi 
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/jegan/mongodb # Replace this with /var/nfs/userxx/mongodb 
    server: 192.168.1.108  # Replace this IP with your Linux Server IP you see in the Remote Desktop connection 
