apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-jegan # Replace 'jegan' with your name
  labels:
    name: jegan  # Replace 'jegan' with your name
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /var/nfs/jegan/redis   # Replace this path with /var/nfs/userxy/redis
    server: 192.168.1.108

